DROP TABLE `blog_posts`;--> statement-breakpoint
DROP TABLE `catalog_price_history`;--> statement-breakpoint
DROP TABLE `catalogs`;--> statement-breakpoint
DROP TABLE `city_knowledge`;--> statement-breakpoint
DROP TABLE `notifications`;--> statement-breakpoint
DROP TABLE `profiles_provider`;--> statement-breakpoint
DROP TABLE `project_docs`;--> statement-breakpoint
DROP TABLE `project_items`;--> statement-breakpoint
DROP TABLE `project_members`;--> statement-breakpoint
DROP TABLE `project_tasks`;--> statement-breakpoint
DROP TABLE `projects`;--> statement-breakpoint
DROP TABLE `quotes`;--> statement-breakpoint
DROP TABLE `ratings`;--> statement-breakpoint
DROP TABLE `rfq_requests`;--> statement-breakpoint
DROP TABLE `social_comments`;--> statement-breakpoint
DROP TABLE `social_group_members`;--> statement-breakpoint
DROP TABLE `social_groups`;--> statement-breakpoint
DROP TABLE `social_posts`;--> statement-breakpoint
DROP TABLE `users`;--> statement-breakpoint
DROP TABLE `verification_docs`;