import { db } from '../index';
import { user, profilesProvider, catalogs, projects } from '../schema';

async function seed() {
  console.log('🌱 Starting seed...');

  // Create provider users
  const providerUsers = [
    {
      id: 'provider_1',
      name: 'Rajesh Tiles & Marbles',
      email: 'rajesh@tilesmarbles.com',
      emailVerified: true,
      userType: 'provider',
      locale: 'en',
      createdAt: new Date('2024-01-15'),
      updatedAt: new Date('2024-01-15'),
    },
    {
      id: 'provider_2',
      name: 'Mumbai Building Supplies',
      email: 'info@mumbaibuild.com',
      emailVerified: true,
      userType: 'provider',
      locale: 'en',
      createdAt: new Date('2024-02-10'),
      updatedAt: new Date('2024-02-10'),
    },
    {
      id: 'provider_3',
      name: 'Delhi Construction Materials',
      email: 'sales@delhiconstruct.com',
      emailVerified: true,
      userType: 'provider',
      locale: 'en',
      createdAt: new Date('2024-03-05'),
      updatedAt: new Date('2024-03-05'),
    },
  ];

  for (const providerUser of providerUsers) {
    await db.insert(user).values(providerUser).onConflictDoNothing();
  }
  console.log('✅ Provider users created');

  // Create provider profiles
  const providerProfiles = [
    {
      userId: 'provider_1',
      shopName: 'Rajesh Tiles & Marbles',
      phone: '+91 98765 43210',
      address: 'Shop 12, MI Road, Jaipur',
      categories: JSON.stringify(['tiles', 'marble', 'granite']),
      brands: JSON.stringify(['Kajaria', 'Somany', 'Johnson']),
      kycStatus: 'verified',
      trustScore: 85,
      description: 'Premium tiles and marbles supplier in Jaipur. 15+ years experience.',
      createdAt: new Date('2024-01-15').toISOString(),
      updatedAt: new Date('2024-01-15').toISOString(),
    },
    {
      userId: 'provider_2',
      shopName: 'Mumbai Building Supplies',
      phone: '+91 98765 43211',
      address: 'Goregaon East, Mumbai',
      categories: JSON.stringify(['cement', 'steel', 'paint']),
      brands: JSON.stringify(['UltraTech', 'ACC', 'Asian Paints']),
      kycStatus: 'verified',
      trustScore: 92,
      description: 'Complete building materials supplier. Wholesale and retail.',
      createdAt: new Date('2024-02-10').toISOString(),
      updatedAt: new Date('2024-02-10').toISOString(),
    },
    {
      userId: 'provider_3',
      shopName: 'Delhi Construction Materials',
      phone: '+91 98765 43212',
      address: 'Lajpat Nagar, Delhi',
      categories: JSON.stringify(['sanitaryware', 'plumbing', 'electrical']),
      brands: JSON.stringify(['Jaquar', 'Kohler', 'Havells']),
      kycStatus: 'verified',
      trustScore: 88,
      description: 'Quality sanitaryware and electrical items. Fast delivery.',
      createdAt: new Date('2024-03-05').toISOString(),
      updatedAt: new Date('2024-03-05').toISOString(),
    },
  ];

  for (const profile of providerProfiles) {
    await db.insert(profilesProvider).values(profile).onConflictDoNothing();
  }
  console.log('✅ Provider profiles created');

  // Create catalogs
  const catalogItems = [
    // Tiles
    {
      providerId: 'provider_1',
      title: 'Kajaria Vitrified Tiles 600x600mm',
      brand: 'Kajaria',
      sku: 'KAJ-VIT-600',
      description: 'Premium vitrified tiles with glossy finish. Perfect for living rooms and bedrooms.',
      price: 85.50,
      currency: 'INR',
      unit: 'sq.ft',
      moq: 100,
      stockStatus: 'in',
      city: 'Jaipur',
      deliveryRadiusKm: 50,
      images: JSON.stringify([]),
      popularityScore: 150,
      createdAt: new Date('2024-01-20').toISOString(),
      updatedAt: new Date('2024-01-20').toISOString(),
    },
    {
      providerId: 'provider_1',
      title: 'Somany Ceramic Floor Tiles',
      brand: 'Somany',
      sku: 'SOM-CER-400',
      description: 'Durable ceramic tiles for high-traffic areas. Anti-slip surface.',
      price: 45.00,
      currency: 'INR',
      unit: 'sq.ft',
      moq: 150,
      stockStatus: 'in',
      city: 'Jaipur',
      deliveryRadiusKm: 50,
      images: JSON.stringify([]),
      popularityScore: 200,
      createdAt: new Date('2024-01-22').toISOString(),
      updatedAt: new Date('2024-01-22').toISOString(),
    },
    {
      providerId: 'provider_1',
      title: 'Italian Marble White Carrara',
      brand: 'Premium',
      sku: 'MAR-CAR-WHT',
      description: 'Imported Italian marble with elegant white veining. Premium quality.',
      price: 320.00,
      currency: 'INR',
      unit: 'sq.ft',
      moq: 50,
      stockStatus: 'limited',
      city: 'Jaipur',
      deliveryRadiusKm: 30,
      images: JSON.stringify([]),
      popularityScore: 80,
      createdAt: new Date('2024-02-01').toISOString(),
      updatedAt: new Date('2024-02-01').toISOString(),
    },
    // Cement
    {
      providerId: 'provider_2',
      title: 'UltraTech OPC 53 Grade Cement',
      brand: 'UltraTech',
      sku: 'UT-OPC-53',
      description: 'High strength OPC cement for all construction needs. 50kg bag.',
      price: 385.00,
      currency: 'INR',
      unit: 'bag',
      moq: 50,
      stockStatus: 'in',
      city: 'Mumbai',
      deliveryRadiusKm: 40,
      images: JSON.stringify([]),
      popularityScore: 300,
      createdAt: new Date('2024-02-15').toISOString(),
      updatedAt: new Date('2024-02-15').toISOString(),
    },
    {
      providerId: 'provider_2',
      title: 'ACC PPC Cement',
      brand: 'ACC',
      sku: 'ACC-PPC-43',
      description: 'Portland Pozzolana Cement for plastering and masonry work.',
      price: 340.00,
      currency: 'INR',
      unit: 'bag',
      moq: 100,
      stockStatus: 'in',
      city: 'Mumbai',
      deliveryRadiusKm: 40,
      images: JSON.stringify([]),
      popularityScore: 250,
      createdAt: new Date('2024-02-18').toISOString(),
      updatedAt: new Date('2024-02-18').toISOString(),
    },
    // Paint
    {
      providerId: 'provider_2',
      title: 'Asian Paints Royale Luxury Emulsion',
      brand: 'Asian Paints',
      sku: 'AP-ROY-LUX',
      description: 'Premium interior emulsion with rich finish. Multiple colors available.',
      price: 650.00,
      currency: 'INR',
      unit: 'liter',
      moq: 10,
      stockStatus: 'in',
      city: 'Mumbai',
      deliveryRadiusKm: 30,
      images: JSON.stringify([]),
      popularityScore: 180,
      createdAt: new Date('2024-03-01').toISOString(),
      updatedAt: new Date('2024-03-01').toISOString(),
    },
    {
      providerId: 'provider_2',
      title: 'Berger Weathercoat Exterior Paint',
      brand: 'Berger',
      sku: 'BER-WEA-EXT',
      description: 'Weather-resistant exterior paint. Protects against rain and sun.',
      price: 480.00,
      currency: 'INR',
      unit: 'liter',
      moq: 20,
      stockStatus: 'in',
      city: 'Mumbai',
      deliveryRadiusKm: 35,
      images: JSON.stringify([]),
      popularityScore: 160,
      createdAt: new Date('2024-03-05').toISOString(),
      updatedAt: new Date('2024-03-05').toISOString(),
    },
    // Sanitaryware
    {
      providerId: 'provider_3',
      title: 'Jaquar One-Piece Toilet',
      brand: 'Jaquar',
      sku: 'JAQ-TOI-001',
      description: 'Modern one-piece toilet with soft-close seat. Water-efficient design.',
      price: 12500.00,
      currency: 'INR',
      unit: 'piece',
      moq: 1,
      stockStatus: 'in',
      city: 'Delhi',
      deliveryRadiusKm: 25,
      images: JSON.stringify([]),
      popularityScore: 90,
      createdAt: new Date('2024-03-10').toISOString(),
      updatedAt: new Date('2024-03-10').toISOString(),
    },
    {
      providerId: 'provider_3',
      title: 'Kohler Designer Basin',
      brand: 'Kohler',
      sku: 'KOH-BAS-DES',
      description: 'Premium designer basin with overflow. Contemporary styling.',
      price: 8500.00,
      currency: 'INR',
      unit: 'piece',
      moq: 1,
      stockStatus: 'in',
      city: 'Delhi',
      deliveryRadiusKm: 25,
      images: JSON.stringify([]),
      popularityScore: 75,
      createdAt: new Date('2024-03-12').toISOString(),
      updatedAt: new Date('2024-03-12').toISOString(),
    },
    {
      providerId: 'provider_3',
      title: 'Jaquar Single Lever Basin Mixer',
      brand: 'Jaquar',
      sku: 'JAQ-MIX-BAS',
      description: 'Chrome-finished basin mixer with ceramic cartridge. Lifetime warranty.',
      price: 4200.00,
      currency: 'INR',
      unit: 'piece',
      moq: 5,
      stockStatus: 'in',
      city: 'Delhi',
      deliveryRadiusKm: 30,
      images: JSON.stringify([]),
      popularityScore: 120,
      createdAt: new Date('2024-03-15').toISOString(),
      updatedAt: new Date('2024-03-15').toISOString(),
    },
    // Additional items
    {
      providerId: 'provider_2',
      title: 'Tata TMT Steel Bars 12mm',
      brand: 'Tata',
      sku: 'TATA-TMT-12',
      description: 'High-strength TMT bars for construction. Corrosion resistant.',
      price: 58.00,
      currency: 'INR',
      unit: 'kg',
      moq: 500,
      stockStatus: 'in',
      city: 'Mumbai',
      deliveryRadiusKm: 50,
      images: JSON.stringify([]),
      popularityScore: 220,
      createdAt: new Date('2024-03-18').toISOString(),
      updatedAt: new Date('2024-03-18').toISOString(),
    },
    {
      providerId: 'provider_3',
      title: 'Havells Modular Switches',
      brand: 'Havells',
      sku: 'HAV-MOD-SW',
      description: 'Premium modular switches with 10A rating. Multiple color options.',
      price: 180.00,
      currency: 'INR',
      unit: 'piece',
      moq: 10,
      stockStatus: 'in',
      city: 'Delhi',
      deliveryRadiusKm: 40,
      images: JSON.stringify([]),
      popularityScore: 140,
      createdAt: new Date('2024-03-20').toISOString(),
      updatedAt: new Date('2024-03-20').toISOString(),
    },
    {
      providerId: 'provider_1',
      title: 'Johnson Tiles 300x450mm Wall',
      brand: 'Johnson',
      sku: 'JOH-WAL-345',
      description: 'Glossy wall tiles for bathroom and kitchen. Easy to clean.',
      price: 38.00,
      currency: 'INR',
      unit: 'sq.ft',
      moq: 100,
      stockStatus: 'in',
      city: 'Jaipur',
      deliveryRadiusKm: 45,
      images: JSON.stringify([]),
      popularityScore: 190,
      createdAt: new Date('2024-03-22').toISOString(),
      updatedAt: new Date('2024-03-22').toISOString(),
    },
    {
      providerId: 'provider_3',
      title: 'Supreme CPVC Pipes 15mm',
      brand: 'Supreme',
      sku: 'SUP-CPVC-15',
      description: 'Hot and cold water CPVC pipes. ISI certified.',
      price: 75.00,
      currency: 'INR',
      unit: 'foot',
      moq: 50,
      stockStatus: 'in',
      city: 'Delhi',
      deliveryRadiusKm: 35,
      images: JSON.stringify([]),
      popularityScore: 110,
      createdAt: new Date('2024-03-25').toISOString(),
      updatedAt: new Date('2024-03-25').toISOString(),
    },
    {
      providerId: 'provider_2',
      title: 'Ambuja Cement PSC',
      brand: 'Ambuja',
      sku: 'AMB-PSC-50',
      description: 'Portland Slag Cement for durable construction. 50kg bag.',
      price: 360.00,
      currency: 'INR',
      unit: 'bag',
      moq: 75,
      stockStatus: 'limited',
      city: 'Mumbai',
      deliveryRadiusKm: 40,
      images: JSON.stringify([]),
      popularityScore: 130,
      createdAt: new Date('2024-03-28').toISOString(),
      updatedAt: new Date('2024-03-28').toISOString(),
    },
  ];

  for (const catalog of catalogItems) {
    await db.insert(catalogs).values(catalog).onConflictDoNothing();
  }
  console.log('✅ Catalogs created');

  // Create consumer users
  const consumerUsers = [
    {
      id: 'consumer_1',
      name: 'Amit Sharma',
      email: 'amit@example.com',
      emailVerified: true,
      userType: 'consumer',
      locale: 'en',
      createdAt: new Date('2024-01-10'),
      updatedAt: new Date('2024-01-10'),
    },
    {
      id: 'consumer_2',
      name: 'Priya Patel',
      email: 'priya@example.com',
      emailVerified: true,
      userType: 'consumer',
      locale: 'en',
      createdAt: new Date('2024-02-05'),
      updatedAt: new Date('2024-02-05'),
    },
    {
      id: 'consumer_3',
      name: 'Rahul Verma',
      email: 'rahul@example.com',
      emailVerified: true,
      userType: 'consumer',
      locale: 'en',
      createdAt: new Date('2024-03-01'),
      updatedAt: new Date('2024-03-01'),
    },
  ];

  for (const consumerUser of consumerUsers) {
    await db.insert(user).values(consumerUser).onConflictDoNothing();
  }
  console.log('✅ Consumer users created');

  // Create projects
  const projectsList = [
    {
      ownerId: 'consumer_1',
      title: 'Luxury Villa Construction - Jaipur',
      address: 'Plot 45, Vaishali Nagar, Jaipur',
      city: 'Jaipur',
      budget: 5500000,
      currency: 'INR',
      status: 'in_progress',
      createdAt: new Date('2024-02-01').toISOString(),
      updatedAt: new Date('2024-11-20').toISOString(),
    },
    {
      ownerId: 'consumer_1',
      title: '3 BHK Apartment Interior Design',
      address: 'Tower B, Prestige Apartments, Mumbai',
      city: 'Mumbai',
      budget: 1200000,
      currency: 'INR',
      status: 'completed',
      createdAt: new Date('2024-06-15').toISOString(),
      updatedAt: new Date('2024-09-30').toISOString(),
    },
    {
      ownerId: 'consumer_2',
      title: 'Office Space Renovation - Gurgaon',
      address: '4th Floor, Cyber Hub, Gurgaon',
      city: 'Gurgaon',
      budget: 2800000,
      currency: 'INR',
      status: 'planning',
      createdAt: new Date('2024-10-10').toISOString(),
      updatedAt: new Date('2024-10-10').toISOString(),
    },
    {
      ownerId: 'consumer_2',
      title: 'Independent House Construction',
      address: 'Sector 21, Greater Noida',
      city: 'Noida',
      budget: 4200000,
      currency: 'INR',
      status: 'in_progress',
      createdAt: new Date('2024-03-20').toISOString(),
      updatedAt: new Date('2024-11-25').toISOString(),
    },
    {
      ownerId: 'consumer_3',
      title: 'Commercial Showroom Interior',
      address: 'Karol Bagh, Delhi',
      city: 'Delhi',
      budget: 3500000,
      currency: 'INR',
      status: 'completed',
      createdAt: new Date('2024-05-10').toISOString(),
      updatedAt: new Date('2024-08-25').toISOString(),
    },
    {
      ownerId: 'consumer_3',
      title: 'Duplex Villa - Bangalore',
      address: 'Whitefield, Bangalore',
      city: 'Bangalore',
      budget: 7500000,
      currency: 'INR',
      status: 'in_progress',
      createdAt: new Date('2024-04-05').toISOString(),
      updatedAt: new Date('2024-11-28').toISOString(),
    },
    {
      ownerId: 'consumer_1',
      title: '2 BHK Flat Renovation',
      address: 'Andheri West, Mumbai',
      city: 'Mumbai',
      budget: 850000,
      currency: 'INR',
      status: 'planning',
      createdAt: new Date('2024-11-01').toISOString(),
      updatedAt: new Date('2024-11-01').toISOString(),
    },
    {
      ownerId: 'consumer_2',
      title: 'Row House Project - Pune',
      address: 'Baner, Pune',
      city: 'Pune',
      budget: 6200000,
      currency: 'INR',
      status: 'in_progress',
      createdAt: new Date('2024-07-15').toISOString(),
      updatedAt: new Date('2024-11-22').toISOString(),
    },
  ];

  for (const project of projectsList) {
    await db.insert(projects).values(project).onConflictDoNothing();
  }
  console.log('✅ Projects created');

  console.log('🎉 Seeding completed successfully!');
}

seed()
  .catch((error) => {
    console.error('❌ Seeding failed:', error);
    process.exit(1);
  });