import { db } from '@/db';
import { catalogs } from '@/db/schema';

async function main() {
    const sampleCatalogs = [
        {
            providerId: 'user_suresh_01',
            title: 'Premium Floor Tiles',
            brand: 'Kajaria',
            sku: 'KAJ-PREM-FL-001',
            description: 'Premium Kajaria floor tiles with high-gloss finish, perfect for modern living rooms and bedrooms. These tiles feature nano-polish technology for superior shine and stain resistance.',
            price: 85.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 100,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                size: '600x600mm',
                finish: 'glossy',
                type: 'vitrified',
                application: 'floor'
            }),
            city: 'Jaipur',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 78,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            providerId: 'user_suresh_01',
            title: 'Vitrified Tiles 600x600mm',
            brand: 'Kajaria',
            sku: 'KAJ-VIT-600-002',
            description: 'High-quality vitrified tiles ideal for residential and commercial spaces. Excellent durability with minimal water absorption.',
            price: 72.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 150,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                size: '600x600mm',
                finish: 'matte',
                type: 'vitrified',
                thickness: '10mm'
            }),
            city: 'Jaipur',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 82,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            providerId: 'user_suresh_01',
            title: 'Ultratech Cement 50kg',
            brand: 'Ultratech',
            sku: 'ULT-OPC-53-001',
            description: 'High-strength OPC 53 Grade cement from Ultratech. Perfect for all structural work including foundations, columns, and beams. Conforms to IS:12269 standards.',
            price: 385.00,
            currency: 'INR',
            unit: 'bag',
            moq: 10,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                grade: '53',
                type: 'OPC',
                weight: '50kg',
                standard: 'IS:12269'
            }),
            city: 'Jaipur',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 95,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            providerId: 'user_suresh_01',
            title: 'ACC Cement 50kg',
            brand: 'ACC',
            sku: 'ACC-OPC-53-001',
            description: 'Premium ACC cement with superior compressive strength. Ideal for concrete works requiring high durability and early strength development.',
            price: 395.00,
            currency: 'INR',
            unit: 'bag',
            moq: 10,
            stockStatus: 'limited',
            attributes: JSON.stringify({
                grade: '53',
                type: 'OPC',
                weight: '50kg'
            }),
            city: 'Jaipur',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 88,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            providerId: 'user_suresh_01',
            title: 'TMT Steel Bars 8mm',
            brand: 'JSW',
            sku: 'JSW-TMT-8-001',
            description: 'JSW TMT bars Fe500D grade, 8mm diameter. Earthquake-resistant with excellent ductility. 12-meter length bars for minimal joints.',
            price: 58.00,
            currency: 'INR',
            unit: 'kg',
            moq: 500,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                grade: 'Fe500D',
                diameter: '8mm',
                length: '12m',
                type: 'TMT'
            }),
            city: 'Jaipur',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 85,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            providerId: 'user_suresh_01',
            title: 'TMT Steel Bars 12mm',
            brand: 'JSW',
            sku: 'JSW-TMT-12-001',
            description: 'Premium JSW TMT bars Fe500D grade, 12mm diameter. Superior bendability and weldability for earthquake-resistant construction.',
            price: 62.00,
            currency: 'INR',
            unit: 'kg',
            moq: 500,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                grade: 'Fe500D',
                diameter: '12mm',
                length: '12m',
                type: 'TMT'
            }),
            city: 'Jaipur',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 90,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            providerId: 'user_suresh_01',
            title: 'Wall Tiles 300x450mm',
            brand: 'Kajaria',
            sku: 'KAJ-WAL-300-001',
            description: 'Designer ceramic wall tiles perfect for bathrooms and kitchens. Multiple contemporary designs available with moisture resistance.',
            price: 48.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 100,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                size: '300x450mm',
                type: 'ceramic',
                application: 'wall',
                finish: 'glossy'
            }),
            city: 'Jaipur',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 75,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            providerId: 'user_suresh_01',
            title: 'Designer Floor Tiles',
            brand: 'Kajaria Eternity',
            sku: 'KAJ-ETR-DSG-001',
            description: 'Premium Kajaria Eternity series with exclusive designs. Large format tiles with digital print technology for luxury spaces.',
            price: 125.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 80,
            stockStatus: 'limited',
            attributes: JSON.stringify({
                size: '800x800mm',
                finish: 'glossy',
                type: 'vitrified',
                series: 'Eternity'
            }),
            city: 'Jaipur',
            deliveryRadiusKm: 25,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 65,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            providerId: 'user_ramesh_01',
            title: 'Italian Marble Statuario',
            brand: 'Premium',
            sku: 'ITA-STA-MAR-001',
            description: 'Luxurious Italian Statuario marble with distinctive white background and bold grey veining. Premium grade imported directly from Italy. Perfect for high-end residential and commercial projects.',
            price: 425.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 200,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                origin: 'Italy',
                type: 'Statuario',
                color: 'white',
                veining: 'grey',
                grade: 'premium'
            }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 55,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            providerId: 'user_ramesh_01',
            title: 'Indian Marble Makrana',
            brand: 'Classic',
            sku: 'IND-MAK-MAR-001',
            description: 'Authentic Makrana white marble from Rajasthan quarries. Same type used in Taj Mahal. Excellent for flooring and wall cladding.',
            price: 180.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 150,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                origin: 'Makrana',
                color: 'white',
                quality: 'first',
                finish: 'polished'
            }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 72,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            providerId: 'user_ramesh_01',
            title: 'Granite Black Galaxy',
            brand: 'Premium',
            sku: 'GRA-BLK-GAL-001',
            description: 'Stunning Black Galaxy granite with golden speckles. Highly durable and heat-resistant, perfect for kitchen countertops and flooring.',
            price: 285.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 100,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                color: 'black',
                pattern: 'galaxy',
                finish: 'polished',
                origin: 'Andhra Pradesh'
            }),
            city: 'Delhi',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 68,
            createdAt: new Date('2024-01-30').toISOString(),
            updatedAt: new Date('2024-01-30').toISOString(),
        },
        {
            providerId: 'user_ramesh_01',
            title: 'Vitrified Tiles Double Charge',
            brand: 'Somany',
            sku: 'SOM-VIT-DC-001',
            description: 'Somany double charge vitrified tiles with extra layer for enhanced durability. Ideal for high-traffic commercial and residential areas.',
            price: 95.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 120,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                size: '600x600mm',
                type: 'double charge',
                finish: 'glossy',
                thickness: '12mm'
            }),
            city: 'Delhi',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 70,
            createdAt: new Date('2024-01-31').toISOString(),
            updatedAt: new Date('2024-01-31').toISOString(),
        },
        {
            providerId: 'user_ramesh_01',
            title: 'Spanish Porcelain Tiles',
            brand: 'Imported',
            sku: 'SPN-POR-IMP-001',
            description: 'Premium imported Spanish porcelain tiles with realistic wood and stone effects. Large format 600x1200mm for contemporary spaces.',
            price: 165.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 150,
            stockStatus: 'limited',
            attributes: JSON.stringify({
                size: '600x1200mm',
                material: 'porcelain',
                origin: 'Spain',
                rectified: true
            }),
            city: 'Delhi',
            deliveryRadiusKm: 25,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 48,
            createdAt: new Date('2024-02-01').toISOString(),
            updatedAt: new Date('2024-02-01').toISOString(),
        },
        {
            providerId: 'user_ramesh_01',
            title: 'Bathroom Wall Tiles',
            brand: 'Kajaria',
            sku: 'KAJ-BAT-WAL-001',
            description: 'Ceramic wall tiles designed specifically for bathrooms. Moisture-resistant with anti-fungal properties and easy-to-clean surface.',
            price: 55.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 80,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                size: '300x450mm',
                type: 'ceramic',
                application: 'bathroom',
                finish: 'matte'
            }),
            city: 'Delhi',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 80,
            createdAt: new Date('2024-02-02').toISOString(),
            updatedAt: new Date('2024-02-02').toISOString(),
        },
        {
            providerId: 'user_ramesh_01',
            title: 'Kitchen Backsplash Tiles',
            brand: 'Designer',
            sku: 'DSG-KIT-BCK-001',
            description: 'Trendy designer tiles perfect for kitchen backsplash. Multiple patterns available with heat and oil resistance.',
            price: 78.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 50,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                size: '300x300mm',
                type: 'ceramic',
                application: 'kitchen backsplash',
                design: 'contemporary'
            }),
            city: 'Delhi',
            deliveryRadiusKm: 25,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 62,
            createdAt: new Date('2024-02-03').toISOString(),
            updatedAt: new Date('2024-02-03').toISOString(),
        },
        {
            providerId: 'user_ramesh_01',
            title: 'Outdoor Tiles Anti-Slip',
            brand: 'Somany',
            sku: 'SOM-OUT-ASL-001',
            description: 'Heavy-duty anti-slip tiles for outdoor areas like balconies and terraces. Weather-resistant with excellent grip.',
            price: 68.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 100,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                size: '400x400mm',
                finish: 'anti-slip',
                application: 'outdoor',
                weatherResistant: true
            }),
            city: 'Delhi',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 65,
            createdAt: new Date('2024-02-04').toISOString(),
            updatedAt: new Date('2024-02-04').toISOString(),
        },
        {
            providerId: 'user_kiran_01',
            title: 'ACC Gold Cement 50kg',
            brand: 'ACC',
            sku: 'ACC-GLD-53-001',
            description: 'ACC Gold Water Shield cement with advanced water-resistant technology. Premium OPC 53 grade for superior concrete strength.',
            price: 410.00,
            currency: 'INR',
            unit: 'bag',
            moq: 20,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                grade: '53',
                type: 'OPC',
                variant: 'Gold Water Shield',
                weight: '50kg'
            }),
            city: 'Mumbai',
            deliveryRadiusKm: 45,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 92,
            createdAt: new Date('2024-02-05').toISOString(),
            updatedAt: new Date('2024-02-05').toISOString(),
        },
        {
            providerId: 'user_kiran_01',
            title: 'Ultratech Super Cement 50kg',
            brand: 'Ultratech',
            sku: 'ULT-SUP-53-001',
            description: 'Ultratech Super with extra strength formulation. Ideal for high-rise buildings and infrastructure projects.',
            price: 420.00,
            currency: 'INR',
            unit: 'bag',
            moq: 20,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                grade: '53',
                type: 'OPC',
                variant: 'Super',
                weight: '50kg'
            }),
            city: 'Mumbai',
            deliveryRadiusKm: 45,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 90,
            createdAt: new Date('2024-02-06').toISOString(),
            updatedAt: new Date('2024-02-06').toISOString(),
        },
        {
            providerId: 'user_kiran_01',
            title: 'TATA Steel TMT Bars 10mm',
            brand: 'TATA Tiscon',
            sku: 'TAT-TMT-10-001',
            description: 'Premium TATA Tiscon TMT bars Fe500 grade, 10mm diameter. Superior corrosion resistance and seismic performance.',
            price: 65.00,
            currency: 'INR',
            unit: 'kg',
            moq: 1000,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                grade: 'Fe500',
                diameter: '10mm',
                length: '12m',
                type: 'TMT',
                brand: 'Tiscon'
            }),
            city: 'Mumbai',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 88,
            createdAt: new Date('2024-02-07').toISOString(),
            updatedAt: new Date('2024-02-07').toISOString(),
        },
        {
            providerId: 'user_kiran_01',
            title: 'TATA Steel TMT Bars 16mm',
            brand: 'TATA Tiscon',
            sku: 'TAT-TMT-16-001',
            description: 'Heavy-duty TATA Tiscon TMT bars Fe500 grade, 16mm diameter. Ideal for structural columns and beams.',
            price: 67.00,
            currency: 'INR',
            unit: 'kg',
            moq: 1000,
            stockStatus: 'limited',
            attributes: JSON.stringify({
                grade: 'Fe500',
                diameter: '16mm',
                length: '12m',
                type: 'TMT'
            }),
            city: 'Mumbai',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 85,
            createdAt: new Date('2024-02-08').toISOString(),
            updatedAt: new Date('2024-02-08').toISOString(),
        },
        {
            providerId: 'user_kiran_01',
            title: 'Asian Paints Royale Emulsion',
            brand: 'Interior',
            sku: 'ASI-ROY-INT-001',
            description: 'Asian Paints Royale luxury interior emulsion with Teflon surface protector. Rich colors and stain-resistant finish.',
            price: 485.00,
            currency: 'INR',
            unit: 'ltr',
            moq: 20,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                type: 'emulsion',
                application: 'interior',
                finish: 'luxury',
                stainResistant: true
            }),
            city: 'Mumbai',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 78,
            createdAt: new Date('2024-02-09').toISOString(),
            updatedAt: new Date('2024-02-09').toISOString(),
        },
        {
            providerId: 'user_kiran_01',
            title: 'Asian Paints Apex Exterior',
            brand: 'Weather Proof',
            sku: 'ASI-APX-EXT-001',
            description: 'Weather-proof exterior emulsion with UV protection and anti-algal properties. Perfect for coastal areas.',
            price: 520.00,
            currency: 'INR',
            unit: 'ltr',
            moq: 20,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                type: 'emulsion',
                application: 'exterior',
                weatherResistant: true,
                UVProtection: true
            }),
            city: 'Mumbai',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 75,
            createdAt: new Date('2024-02-10').toISOString(),
            updatedAt: new Date('2024-02-10').toISOString(),
        },
        {
            providerId: 'user_kiran_01',
            title: 'Birla White Cement 25kg',
            brand: 'Premium',
            sku: 'BIR-WHT-25-001',
            description: 'Premium Birla White cement for decorative finishes and tile fixing. Exceptional whiteness and smooth texture.',
            price: 625.00,
            currency: 'INR',
            unit: 'bag',
            moq: 5,
            stockStatus: 'limited',
            attributes: JSON.stringify({
                type: 'white cement',
                weight: '25kg',
                application: 'decorative'
            }),
            city: 'Mumbai',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 58,
            createdAt: new Date('2024-02-11').toISOString(),
            updatedAt: new Date('2024-02-11').toISOString(),
        },
        {
            providerId: 'user_kiran_01',
            title: 'Ready Mix Concrete M25',
            brand: 'Standard',
            sku: 'RMC-M25-STD-001',
            description: 'M25 grade ready-mix concrete for structural applications. Factory-mixed for consistent quality with proper test certificates.',
            price: 4200.00,
            currency: 'INR',
            unit: 'cubic meter',
            moq: 1,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                grade: 'M25',
                type: 'structural',
                slump: '100-150mm'
            }),
            city: 'Mumbai',
            deliveryRadiusKm: 25,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 72,
            createdAt: new Date('2024-02-12').toISOString(),
            updatedAt: new Date('2024-02-12').toISOString(),
        },
        {
            providerId: 'user_deepak_01',
            title: 'Hindware Sanitaryware Set',
            brand: 'Premium',
            sku: 'HIN-SAN-SET-001',
            description: 'Complete Hindware sanitaryware set including WC, basin, and fittings. Premium ceramic with soft-close seat covers.',
            price: 12500.00,
            currency: 'INR',
            unit: 'set',
            moq: 1,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                type: 'complete set',
                items: 'WC, basin, fittings',
                finish: 'white',
                seatType: 'soft-close'
            }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 60,
            createdAt: new Date('2024-02-13').toISOString(),
            updatedAt: new Date('2024-02-13').toISOString(),
        },
        {
            providerId: 'user_deepak_01',
            title: 'Jaquar Bathroom Fittings',
            brand: 'Luxury',
            sku: 'JAQ-FIT-LUX-001',
            description: 'Luxury Jaquar bathroom fittings set with chrome finish. Includes faucets, shower, and accessories with ceramic disc technology.',
            price: 8900.00,
            currency: 'INR',
            unit: 'set',
            moq: 1,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                type: 'fittings set',
                finish: 'chrome',
                cartridge: 'ceramic disc',
                warranty: '10 years'
            }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 65,
            createdAt: new Date('2024-02-14').toISOString(),
            updatedAt: new Date('2024-02-14').toISOString(),
        },
        {
            providerId: 'user_deepak_01',
            title: 'Havells Modular Switches',
            brand: 'Crabtree',
            sku: 'HAV-CRA-6A-001',
            description: 'Havells Crabtree modular switches 6A with fire-retardant body. Premium quality with smooth operation and elegant design.',
            price: 85.00,
            currency: 'INR',
            unit: 'piece',
            moq: 50,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                rating: '6A',
                type: 'modular',
                material: 'polycarbonate',
                fireRetardant: true
            }),
            city: 'Bangalore',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 88,
            createdAt: new Date('2024-02-15').toISOString(),
            updatedAt: new Date('2024-02-15').toISOString(),
        },
        {
            providerId: 'user_deepak_01',
            title: 'Legrand Switches Arteor',
            brand: 'Premium',
            sku: 'LEG-ART-6A-001',
            description: 'Legrand Arteor premium modular switches with contemporary design. Features shuttered sockets and tested for 100,000+ operations.',
            price: 145.00,
            currency: 'INR',
            unit: 'piece',
            moq: 30,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                rating: '6A',
                series: 'Arteor',
                design: 'contemporary',
                operations: '100000+'
            }),
            city: 'Bangalore',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 68,
            createdAt: new Date('2024-02-16').toISOString(),
            updatedAt: new Date('2024-02-16').toISOString(),
        },
        {
            providerId: 'user_deepak_01',
            title: 'Century Ply Marine Plywood 18mm',
            brand: 'BWP Grade',
            sku: 'CEN-MAR-18-001',
            description: 'Century marine grade plywood 18mm BWP. Boiling water proof for kitchen cabinets and bathroom vanities. 8x4 feet sheets.',
            price: 125.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 50,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                grade: 'marine',
                thickness: '18mm',
                size: '8x4 feet',
                type: 'BWP',
                waterproof: true
            }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 75,
            createdAt: new Date('2024-02-17').toISOString(),
            updatedAt: new Date('2024-02-17').toISOString(),
        },
        {
            providerId: 'user_deepak_01',
            title: 'Greenply MR Plywood 12mm',
            brand: 'Moisture Resistant',
            sku: 'GRE-MR-12-001',
            description: 'Greenply MR grade plywood 12mm for interior furniture and partitions. Moisture-resistant with smooth finish. 8x4 feet sheets.',
            price: 95.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 50,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({
                grade: 'MR',
                thickness: '12mm',
                size: '8x4 feet',
                moistureResistant: true
            }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 80,
            createdAt: new Date('2024-02-18').toISOString(),
            updatedAt: new Date('2024-02-18').toISOString(),
        }
    ];

    await db.insert(catalogs).values(sampleCatalogs);
    
    console.log('✅ Catalogs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});