import { db } from '@/db';
import { catalogs } from '@/db/schema';

async function main() {
    const sampleCatalogs = [
        {
            providerId: 'provider_jpr_01',
            title: 'Kajaria Vitrified Floor Tiles 600x600mm Glossy Premium',
            brand: 'Kajaria',
            sku: 'KAJ-VIT-600-GL',
            description: 'Premium vitrified floor tiles with nano polish finish. Perfect for living rooms and bedrooms. These tiles feature a high-gloss surface that reflects light beautifully, creating an elegant ambiance in any space. The nano-polished technology ensures stain resistance and easy maintenance. Designed with precision for uniform sizing and minimal wastage during installation. Ideal for modern homes and commercial spaces seeking a luxurious look with durability that lasts for years.',
            price: 75.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 100,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ size: '600x600mm', finish: 'glossy', type: 'vitrified', thickness: '10mm', waterAbsorption: '<0.5%' }),
            city: 'Jaipur',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 85,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            providerId: 'provider_jpr_01',
            title: 'Kajaria Designer Wall Tiles 300x450mm Ceramic',
            brand: 'Kajaria',
            sku: 'KAJ-CER-300',
            description: 'Designer ceramic wall tiles perfect for bathroom and kitchen applications. These tiles feature contemporary patterns and color options that complement modern interior designs. The ceramic surface is resistant to moisture and chemicals, making them ideal for wet areas. Easy to clean and maintain with standard household cleaners. The 300x450mm size is a popular choice for creating stunning wall patterns with minimal grout lines. Suitable for both residential and commercial projects.',
            price: 52.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 75,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ size: '300x450mm', finish: 'matte', type: 'ceramic', application: 'wall', design: 'contemporary' }),
            city: 'Jaipur',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 72,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            providerId: 'provider_jpr_01',
            title: 'Italian Carrara White Marble Premium Grade 18mm',
            brand: 'Italian Marble',
            sku: 'ITA-CAR-WHT',
            description: 'Luxurious Italian Carrara white marble with distinctive gray veining. This premium grade marble is sourced directly from quarries in Italy, ensuring authentic quality and beauty. The 18mm thickness provides structural integrity for various applications including flooring, wall cladding, and countertops. Each slab is unique with natural veining patterns that add character to your space. Perfect for high-end residential projects, hotels, and commercial spaces. The marble\'s timeless elegance and durability make it a worthwhile investment that enhances property value.',
            price: 380.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 50,
            stockStatus: 'limited',
            attributes: JSON.stringify({ origin: 'Italy', color: 'white', veining: 'gray', thickness: '18mm', finish: 'polished', grade: 'premium' }),
            city: 'Jaipur',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 65,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            providerId: 'provider_jpr_01',
            title: 'Indian Makrana White Marble First Quality',
            brand: 'Indian Marble',
            sku: 'IND-MAK-WHT',
            description: 'Authentic Makrana white marble, the same type used in the iconic Taj Mahal. This first quality marble is sourced from Rajasthan quarries and represents the finest Indian craftsmanship. Known for its pure white color and exceptional durability, Makrana marble develops a natural shine over time. The stone is resistant to weathering and maintains its beauty for generations. Ideal for flooring, temples, monuments, and luxury interiors. Each piece is carefully selected to ensure consistent quality and minimal imperfections. A perfect choice for projects seeking traditional elegance.',
            price: 240.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 60,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ origin: 'Makrana, Rajasthan', color: 'white', quality: 'first', finish: 'polished', durability: 'high' }),
            city: 'Jaipur',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 78,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            providerId: 'provider_jpr_01',
            title: 'Ultratech OPC 53 Grade Cement 50kg Bags',
            brand: 'Ultratech',
            sku: 'ULT-OPC-53',
            description: 'High-strength Ordinary Portland Cement (OPC) 53 Grade from Ultratech, India\'s leading cement manufacturer. This premium cement offers superior compressive strength, making it ideal for structural concrete work, high-rise buildings, and projects requiring exceptional durability. The 53 grade ensures faster strength development, allowing for quicker construction timelines. Manufactured with stringent quality controls to meet IS:12269 standards. Each 50kg bag is moisture-resistant and easy to handle. Perfect for foundations, columns, beams, and all load-bearing structures. Trusted by engineers and contractors nationwide for consistent performance.',
            price: 395.00,
            currency: 'INR',
            unit: 'bag',
            moq: 20,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ grade: '53', type: 'OPC', weight: '50kg', standard: 'IS:12269', strength: 'high' }),
            city: 'Jaipur',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 92,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            providerId: 'provider_jpr_01',
            title: 'JSW TMT Steel Bars Fe550D 12mm 12m Length',
            brand: 'JSW Steel',
            sku: 'JSW-TMT-12',
            description: 'Premium quality Thermo-Mechanically Treated (TMT) steel bars from JSW Steel, one of India\'s most trusted steel manufacturers. Fe550D grade offers excellent ductility and weldability, making it perfect for earthquake-resistant construction. The 12mm diameter bars are ideal for residential construction, including slabs, beams, and columns. Each bar is 12 meters in length, reducing wastage and joints in construction. The TMT process ensures a tough outer surface with a soft inner core, providing superior strength and flexibility. Conforms to IS:1786 standards with consistent quality across batches.',
            price: 62.00,
            currency: 'INR',
            unit: 'kg',
            moq: 500,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ grade: 'Fe550D', diameter: '12mm', length: '12m', type: 'TMT', standard: 'IS:1786', seismicResistant: true }),
            city: 'Jaipur',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 88,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            providerId: 'provider_jpr_01',
            title: 'Black Galaxy Granite Premium Polished Slabs',
            brand: 'Granite',
            sku: 'GRN-BLK-GAL',
            description: 'Stunning Black Galaxy granite with characteristic golden speckles that resemble stars in the night sky. This premium granite is sourced from quarries in Andhra Pradesh and is known for its exceptional beauty and durability. The polished finish enhances the natural sparkle of the stone, creating a luxurious appearance. Highly resistant to scratches, heat, and stains, making it perfect for kitchen countertops, flooring, and wall cladding. The dense composition ensures minimal water absorption and long-lasting performance. Each slab is carefully inspected for quality and consistency in pattern.',
            price: 185.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 40,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ color: 'black', pattern: 'galaxy', finish: 'polished', origin: 'Andhra Pradesh', hardness: 'high', porosity: 'low' }),
            city: 'Jaipur',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 70,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            providerId: 'provider_jpr_01',
            title: 'ACC PPC Cement 50kg Weatherproof Grade',
            brand: 'ACC',
            sku: 'ACC-PPC-50',
            description: 'Portland Pozzolana Cement (PPC) from ACC, specially formulated for enhanced durability and weather resistance. This cement offers improved resistance to sulfate attacks and chloride penetration, making it ideal for coastal areas and structures exposed to harsh environmental conditions. The pozzolanic materials provide better workability and reduced heat of hydration, perfect for mass concreting works. Meets IS:1489 standards with consistent quality. Each 50kg bag is designed for easy handling and storage. Excellent for plastering, masonry work, and general construction where long-term durability is essential. Eco-friendly with lower carbon footprint.',
            price: 375.00,
            currency: 'INR',
            unit: 'bag',
            moq: 20,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ type: 'PPC', grade: 'weatherproof', weight: '50kg', standard: 'IS:1489', sulfateResistant: true }),
            city: 'Jaipur',
            deliveryRadiusKm: 40,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 85,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
        {
            providerId: 'provider_del_01',
            title: 'Somany Vitrified Tiles 800x800mm Matte Finish',
            brand: 'Somany',
            sku: 'SOM-VIT-800',
            description: 'Large format vitrified tiles from Somany with contemporary matte finish. The 800x800mm size creates a seamless look with fewer grout lines, perfect for modern minimalist interiors. These tiles feature nano-coating technology that provides stain resistance and easy maintenance. The matte surface offers excellent slip resistance, making them suitable for both indoor and outdoor applications. Uniform color distribution and precise dimensions ensure flawless installation. Ideal for living rooms, lobbies, and commercial spaces requiring a sophisticated aesthetic. The vitrified body ensures low water absorption and high mechanical strength.',
            price: 95.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 80,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ size: '800x800mm', finish: 'matte', type: 'vitrified', thickness: '12mm', slipResistance: 'high', rectified: true }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 80,
            createdAt: new Date('2024-01-20').toISOString(),
            updatedAt: new Date('2024-01-20').toISOString(),
        },
        {
            providerId: 'provider_del_01',
            title: 'Kajaria Bathroom Tiles 300x300mm Anti-Skid',
            brand: 'Kajaria',
            sku: 'KAJ-BAT-300',
            description: 'Specially designed anti-skid bathroom tiles from Kajaria, ensuring safety in wet areas. The 300x300mm format is perfect for bathroom floors and provides excellent grip even when wet. The surface texture is engineered to prevent slipping while remaining easy to clean and maintain. These tiles are resistant to chemicals commonly found in cleaning products and maintain their appearance over years of use. Available in multiple contemporary designs that complement modern bathroom aesthetics. The ceramic body ensures durability and resistance to moisture penetration. Ideal for residential bathrooms, hotels, and commercial washrooms.',
            price: 38.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 60,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ size: '300x300mm', finish: 'anti-skid', type: 'ceramic', application: 'bathroom floor', slipRating: 'R11', moistureResistant: true }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 88,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            providerId: 'provider_del_01',
            title: 'Hindware European WC Complete Set with Soft Close Seat',
            brand: 'Hindware',
            sku: 'HIN-WC-EUR',
            description: 'Premium European-style wall-hung water closet from Hindware, featuring contemporary design and superior functionality. The complete set includes the WC pan, concealed cistern, flush plate, and soft-close seat cover. The wall-hung design creates a floating effect, making bathroom cleaning easier and providing a modern aesthetic. The soft-close mechanism prevents slamming and ensures durability of the seat. Dual flush technology offers water-saving options with 3/6 liter flush volumes. The high-gloss ceramic finish resists stains and maintains its pristine appearance. Includes all necessary mounting hardware and installation instructions. Perfect for premium residential projects and luxury hotels.',
            price: 11500.00,
            currency: 'INR',
            unit: 'piece',
            moq: 1,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ type: 'wall-hung', style: 'European', flushType: 'dual', flushVolume: '3/6L', seatType: 'soft-close', color: 'white', warranty: '10 years' }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 75,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            providerId: 'provider_del_01',
            title: 'Jaquar Single Lever Basin Mixer Chrome Finish Premium',
            brand: 'Jaquar',
            sku: 'JAQ-MIX-CHR',
            description: 'Elegant single lever basin mixer from Jaquar with premium chrome finish. This contemporary faucet features smooth operation with precise temperature and flow control using a single lever. The ceramic disc cartridge ensures drip-free performance and longevity with over 500,000 cycles. The chrome finish is achieved through multiple layers of plating, providing exceptional resistance to corrosion and tarnishing. The aerator provides a soft, splash-free water stream while saving water. Easy to install with flexible connectors and comes with all necessary accessories. Perfect for modern bathrooms seeking functionality combined with aesthetic appeal. Backed by manufacturer warranty.',
            price: 3850.00,
            currency: 'INR',
            unit: 'piece',
            moq: 1,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ type: 'single-lever', finish: 'chrome', mounting: 'deck-mounted', cartridge: 'ceramic disc', aerator: true, warranty: '10 years' }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 82,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            providerId: 'provider_del_01',
            title: 'Hindware Wall Mounted Designer Basin White Ceramic',
            brand: 'Hindware',
            sku: 'HIN-BAS-WAL',
            description: 'Contemporary wall-mounted basin from Hindware with designer aesthetics and practical functionality. The white ceramic construction with high-gloss finish provides a clean, modern look that complements any bathroom decor. The wall-mounted design saves floor space and creates an airy feel, perfect for compact bathrooms. The basin features an integrated overflow system and pre-drilled faucet hole. The ceramic material is resistant to staining, scratching, and chemical damage from cleaning products. Comes with concealed wall brackets for secure mounting. The smooth curves and clean lines make cleaning effortless. Ideal for modern homes, apartments, and commercial spaces. Includes installation guide.',
            price: 4200.00,
            currency: 'INR',
            unit: 'piece',
            moq: 1,
            stockStatus: 'limited',
            attributes: JSON.stringify({ type: 'wall-mounted', material: 'ceramic', color: 'white', finish: 'glossy', overflow: true, faucetHoles: 1, warranty: '5 years' }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 68,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            providerId: 'provider_del_01',
            title: 'Italian Statuario Marble with Gold Veins Premium',
            brand: 'Italian Marble',
            sku: 'ITA-STA-GLD',
            description: 'Exquisite Italian Statuario marble featuring dramatic gold veining on white background. This ultra-premium marble is sourced from select quarries in Italy and represents the pinnacle of natural stone luxury. Each slab is unique with bold, distinctive veining patterns that create stunning visual impact. The marble\'s rarity and beauty make it highly sought after for luxury residential projects, five-star hotels, and high-end commercial spaces. Perfect for feature walls, flooring in grand entrances, and statement countertops. The stone requires professional installation and periodic sealing to maintain its pristine appearance. An investment piece that significantly enhances property value and prestige.',
            price: 450.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 50,
            stockStatus: 'limited',
            attributes: JSON.stringify({ origin: 'Italy', type: 'Statuario', color: 'white', veining: 'gold', grade: 'ultra-premium', finish: 'polished', rarity: 'high' }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 60,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            providerId: 'provider_del_01',
            title: 'Spanish Porcelain Tiles 600x1200mm Large Format',
            brand: 'Spanish Tiles',
            sku: 'SPN-POR-1200',
            description: 'Premium large format porcelain tiles from Spain, featuring contemporary designs and superior technical properties. The 600x1200mm size creates a dramatic effect with minimal grout lines, perfect for modern architectural spaces. These tiles are manufactured using advanced digital printing technology that creates realistic stone and wood effects. The porcelain body is highly dense with extremely low water absorption, making them suitable for both interior and exterior applications. Resistant to frost, stains, and UV rays. The rectified edges ensure precise installation with thin grout joints. Ideal for living rooms, commercial lobbies, and feature walls. Each tile is calibrated for uniform thickness.',
            price: 125.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 70,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ size: '600x1200mm', material: 'porcelain', origin: 'Spain', waterAbsorption: '<0.5%', frostResistant: true, rectified: true, thickness: '10mm' }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 72,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            providerId: 'provider_del_01',
            title: 'Nitco Parking Tiles 400x400mm Heavy Duty Anti-Skid',
            brand: 'Nitco',
            sku: 'NIT-PRK-400',
            description: 'Industrial-grade parking tiles from Nitco, specifically engineered for vehicular traffic areas. These heavy-duty tiles feature superior load-bearing capacity and excellent resistance to impact and abrasion. The anti-skid surface texture provides reliable grip for vehicles in all weather conditions while allowing water drainage. The 400x400mm size is ideal for parking lots, driveways, and industrial areas. Made from high-quality vitrified material with enhanced thickness for durability. Resistant to oil, grease, and chemical spills commonly found in parking areas. The tiles maintain their appearance even under heavy use. Easy to install and replace individual tiles if needed. Meets international standards for commercial parking applications.',
            price: 45.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 100,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ size: '400x400mm', type: 'vitrified', application: 'parking', finish: 'anti-skid', loadCapacity: 'heavy-duty', thickness: '14mm', oilResistant: true }),
            city: 'Delhi',
            deliveryRadiusKm: 35,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 78,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            providerId: 'provider_mum_01',
            title: 'ACC Gold Cement 50kg Premium Quality OPC 53',
            brand: 'ACC',
            sku: 'ACC-GLD-53',
            description: 'ACC Gold Water Shield cement represents the pinnacle of cement technology with advanced formulation for superior performance. This premium OPC 53 grade cement offers exceptional compressive strength development, making it ideal for high-rise buildings, bridges, and infrastructure projects. The proprietary water-resistant technology provides enhanced durability in aggressive environments. Features consistent particle size distribution for better workability and reduced water demand. Manufactured using state-of-the-art facilities with stringent quality control at every stage. Perfect for structural concrete, pre-stressed concrete, and rapid construction projects. Each 50kg bag is designed with moisture-resistant packaging. Conforms to IS:12269 with superior performance characteristics. Trusted by leading construction companies.',
            price: 385.00,
            currency: 'INR',
            unit: 'bag',
            moq: 20,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ grade: '53', type: 'OPC', variant: 'Gold Water Shield', weight: '50kg', standard: 'IS:12269', waterResistant: true, strength: 'ultra-high' }),
            city: 'Mumbai',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 90,
            createdAt: new Date('2024-01-21').toISOString(),
            updatedAt: new Date('2024-01-21').toISOString(),
        },
        {
            providerId: 'provider_mum_01',
            title: 'TATA Steel TMT Bars Fe500 16mm Earthquake Resistant',
            brand: 'TATA Steel',
            sku: 'TAT-TMT-16',
            description: 'Premium TMT bars from TATA Steel with Fe500 grade specification, engineered for superior seismic resistance. These 16mm diameter bars are manufactured using advanced Tempcore technology that creates an optimal combination of strength and ductility. The unique metallurgical structure provides excellent bendability and weldability, crucial for earthquake-resistant construction. Each bar undergoes rigorous quality testing to ensure consistent performance. The corrosion-resistant properties extend the lifespan of reinforced concrete structures. Ideal for multi-story buildings, industrial structures, and infrastructure projects in seismic zones. Conforms to IS:1786 standards with third-party certification. The bars feature distinctive brand markings for easy identification. Supplied in 12-meter lengths to minimize joints and wastage.',
            price: 58.00,
            currency: 'INR',
            unit: 'kg',
            moq: 1000,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ grade: 'Fe500', diameter: '16mm', length: '12m', type: 'TMT', technology: 'Tempcore', seismicResistant: true, standard: 'IS:1786', corrosionResistant: true }),
            city: 'Mumbai',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 92,
            createdAt: new Date('2024-01-22').toISOString(),
            updatedAt: new Date('2024-01-22').toISOString(),
        },
        {
            providerId: 'provider_mum_01',
            title: 'Asian Paints Royale Luxury Emulsion 20 Liter Premium Interior',
            brand: 'Asian Paints',
            sku: 'ASI-ROY-20L',
            description: 'Asian Paints Royale represents luxury interior painting with an exquisite range of premium finishes. This 20-liter pack offers exceptional coverage and a smooth, velvety texture that enhances the elegance of any interior space. The advanced Teflon surface protector technology provides superior stain resistance, making walls easy to clean and maintain. The paint has low VOC content, ensuring better indoor air quality and safety for families. Available in an extensive color palette with rich, vibrant hues. The formulation ensures excellent durability with resistance to fungal growth and chalking. Perfect for living rooms, bedrooms, and premium residential projects. One coat provides excellent coverage, reducing application time and costs.',
            price: 545.00,
            currency: 'INR',
            unit: 'ltr',
            moq: 10,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ type: 'emulsion', application: 'interior', volume: '20L', finish: 'luxury', stainResistant: true, VOC: 'low', coverage: '140-160 sqft/ltr', warranty: '5 years' }),
            city: 'Mumbai',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 86,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            providerId: 'provider_mum_01',
            title: 'Asian Paints Apex Exterior Emulsion 20 Liter Weather Shield',
            brand: 'Asian Paints',
            sku: 'ASI-APX-20L',
            description: 'Asian Paints Apex Exterior Emulsion with advanced weather shield technology for superior protection against harsh environmental conditions. This premium exterior paint provides excellent resistance to UV rays, rain, pollution, and temperature fluctuations. The special formulation includes anti-algal and anti-fungal properties that prevent unsightly growth on exterior walls. The paint maintains its color vibrancy and finish for years, even in coastal and industrial areas. The smooth finish resists dirt accumulation, keeping exteriors looking fresh longer. Excellent coverage and easy application make it a preferred choice for contractors. The 20-liter pack is economical for large projects. Suitable for all types of exterior wall surfaces including concrete, plaster, and brick.',
            price: 425.00,
            currency: 'INR',
            unit: 'ltr',
            moq: 10,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ type: 'emulsion', application: 'exterior', volume: '20L', weatherResistant: true, UVProtection: true, antiFungal: true, coverage: '120-140 sqft/ltr', warranty: '7 years' }),
            city: 'Mumbai',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 82,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            providerId: 'provider_mum_01',
            title: 'Century Ply Marine Grade 19mm 8x4ft BWP Waterproof',
            brand: 'Century Ply',
            sku: 'CEN-MAR-19',
            description: 'Premium marine grade plywood from Century Ply, manufactured to withstand extreme moisture conditions. This 19mm BWP (Boiling Water Proof) plywood is bonded with phenol formaldehyde resin that provides superior water resistance. The 8x4 feet sheets are made from carefully selected hardwood veneers with uniform thickness and grain pattern. Ideal for kitchen cabinets, bathroom vanities, outdoor furniture, and coastal area construction. The plywood undergoes rigorous boiling water test to ensure complete waterproof integrity. Features smooth surface finish on both sides, ready for laminate application or painting. The core construction ensures excellent screw holding capacity and minimal warping. Certified by international standards for formaldehyde emission and structural quality. A premium choice for long-lasting furniture and fixtures.',
            price: 145.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 10,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ grade: 'marine', thickness: '19mm', size: '8x4 feet', type: 'BWP', waterproof: true, resin: 'phenolic', core: 'hardwood', emission: 'E1 grade' }),
            city: 'Mumbai',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 80,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            providerId: 'provider_mum_01',
            title: 'Greenply MR Grade Plywood 12mm 8x4ft Moisture Resistant',
            brand: 'Greenply',
            sku: 'GRE-MR-12',
            description: 'Greenply MR (Moisture Resistant) grade plywood designed for interior applications where moisture exposure is moderate. This 12mm thickness is perfect for furniture, wardrobes, partitions, and interior decorative panels. Manufactured using quality hardwood veneers bonded with urea formaldehyde resin that provides good moisture resistance for indoor use. The plywood features smooth surface finish with minimal defects, making it ideal for laminate and veneer applications. The uniform thickness ensures precise fitting and professional results. Features good bending strength and dimensional stability under normal indoor conditions. The 8x4 feet size is standard for furniture making and interior carpentry work. Conforms to IS:303 specifications with low formaldehyde emission. An economical choice for quality interior woodwork.',
            price: 95.00,
            currency: 'INR',
            unit: 'sqft',
            moq: 15,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ grade: 'MR', thickness: '12mm', size: '8x4 feet', moistureResistant: true, resin: 'urea formaldehyde', application: 'interior', standard: 'IS:303', emission: 'E1 grade' }),
            city: 'Mumbai',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 85,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            providerId: 'provider_mum_01',
            title: 'Birla White Cement 50kg Premium Quality',
            brand: 'Birla',
            sku: 'BIR-WHT-50',
            description: 'Birla White Cement, India\'s leading white cement brand known for exceptional whiteness and strength. This premium quality cement is manufactured using carefully selected raw materials that ensure consistent white color and superior performance. Ideal for creating bright, elegant finishes in plastering, tile fixing, and decorative applications. The fine particle size provides excellent workability and smooth surface finish. Perfect for white washing, creating decorative patterns, and architectural elements requiring pristine white appearance. The cement provides good adhesion to various substrates including concrete, plaster, and tiles. Can be mixed with color pigments for custom tinted finishes. Each 50kg bag maintains its quality with proper moisture-resistant packaging. Widely used in residential, commercial, and heritage restoration projects.',
            price: 685.00,
            currency: 'INR',
            unit: 'bag',
            moq: 5,
            stockStatus: 'limited',
            attributes: JSON.stringify({ type: 'white cement', weight: '50kg', whiteness: 'premium', application: 'decorative', fineness: 'high', strength: 'good', uses: ['plastering', 'tile fixing', 'decorative'] }),
            city: 'Mumbai',
            deliveryRadiusKm: 50,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 75,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            providerId: 'provider_blr_01',
            title: 'Havells Modular Switches Crabtree 6A White Premium',
            brand: 'Havells',
            sku: 'HAV-CRA-6A',
            description: 'Havells Crabtree modular switches represent the perfect blend of safety, style, and functionality. These premium 6A switches feature robust construction with fire-retardant polycarbonate body that ensures long-lasting performance and safety. The smooth operation mechanism provides tactile feedback with every use. The white finish maintains its pristine appearance over years without yellowing. Features universal mounting system compatible with standard modular boxes. The switches are designed to handle Indian voltage fluctuations and provide reliable performance. Child-safe shuttered sockets prevent accidental contact. Easy to install and maintain with screwless cover plates for seamless aesthetics. Backed by comprehensive warranty and excellent service network. Perfect for residential and commercial projects requiring quality electrical fittings.',
            price: 125.00,
            currency: 'INR',
            unit: 'piece',
            moq: 20,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ brand: 'Crabtree by Havells', rating: '6A', color: 'white', material: 'polycarbonate', fireRetardant: true, childSafe: true, warranty: '10 years' }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 88,
            createdAt: new Date('2024-01-23').toISOString(),
            updatedAt: new Date('2024-01-23').toISOString(),
        },
        {
            providerId: 'provider_blr_01',
            title: 'Legrand Britzy Modular Switches Premium Range 6A',
            brand: 'Legrand',
            sku: 'LEG-BRI-6A',
            description: 'Legrand Britzy modular switches combine European design excellence with Indian application requirements. These premium 6A switches feature contemporary styling with slim profile and elegant finish. The switches are manufactured using high-grade materials that ensure durability and consistent performance. The innovative design includes safe shuttered sockets and secure terminal connections. The switching mechanism is tested for over 100,000 operations ensuring long service life. The glossy white finish is UV stabilized to prevent discoloration. Compatible with standard modular electrical boxes for easy installation. Features clear ON/OFF markings and smooth operation. The comprehensive range includes switches, sockets, and accessories for complete electrical solutions. Ideal for modern homes and offices seeking reliable, stylish electrical fittings.',
            price: 95.00,
            currency: 'INR',
            unit: 'piece',
            moq: 25,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ brand: 'Britzy by Legrand', rating: '6A', design: 'contemporary', material: 'high-grade plastic', shuttered: true, operations: '100000+', warranty: '10 years' }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 82,
            createdAt: new Date('2024-01-24').toISOString(),
            updatedAt: new Date('2024-01-24').toISOString(),
        },
        {
            providerId: 'provider_blr_01',
            title: 'Havells LED Panel Light 36W Square 600x600mm Cool White',
            brand: 'Havells',
            sku: 'HAV-LED-36W',
            description: 'Havells LED panel light delivers uniform, flicker-free illumination perfect for modern office spaces and commercial environments. This 36W square panel with 600x600mm dimensions fits standard false ceiling grids seamlessly. The cool white light output provides excellent visibility and reduces eye strain during extended working hours. Features energy-efficient LED technology that consumes significantly less power compared to traditional fluorescent lighting. The slim profile design with white powder-coated aluminum frame offers contemporary aesthetics. The diffuser ensures even light distribution without hot spots or shadows. Long lifespan of 25,000+ hours reduces maintenance costs and replacement frequency. Easy installation with mounting clips and driver included. Suitable for offices, hospitals, educational institutions, and retail spaces. Certified for electrical safety standards.',
            price: 1450.00,
            currency: 'INR',
            unit: 'piece',
            moq: 5,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ wattage: '36W', size: '600x600mm', shape: 'square', colorTemp: '6500K', lumens: '3200lm', lifespan: '25000+ hours', efficiency: 'high', warranty: '2 years' }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 78,
            createdAt: new Date('2024-01-25').toISOString(),
            updatedAt: new Date('2024-01-25').toISOString(),
        },
        {
            providerId: 'provider_blr_01',
            title: 'Berger Weathercoat Exterior Emulsion Paint 20 Liter All Weather',
            brand: 'Berger',
            sku: 'BER-WEA-20L',
            description: 'Berger Weathercoat is an advanced exterior emulsion formulated to withstand diverse Indian weather conditions. This all-weather paint provides exceptional protection against sun, rain, wind, and pollution. The special silicon-modified acrylic formulation creates a breathable film that prevents moisture accumulation while resisting water penetration. Features anti-algal and anti-fungal additives that prevent biological growth on exterior walls. The paint maintains its color fastness and finish even under prolonged UV exposure. Excellent coverage ensures economical usage with professional results. The 20-liter pack is ideal for large exterior painting projects. Suitable for application on concrete, cement plaster, brick, and previously painted surfaces. Easy to apply with brush, roller, or spray. Dries quickly allowing for faster project completion. Trusted by professional painters nationwide.',
            price: 380.00,
            currency: 'INR',
            unit: 'ltr',
            moq: 10,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ type: 'exterior emulsion', volume: '20L', weatherResistant: true, UVProtection: true, breathable: true, antiFungal: true, coverage: '115-130 sqft/ltr', warranty: '6 years' }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 80,
            createdAt: new Date('2024-01-26').toISOString(),
            updatedAt: new Date('2024-01-26').toISOString(),
        },
        {
            providerId: 'provider_blr_01',
            title: 'Greenply Teak Veneer Flush Doors 7x3ft Premium Quality',
            brand: 'Greenply',
            sku: 'GRE-TEK-7X3',
            description: 'Premium quality flush doors from Greenply featuring natural teak veneer finish that brings warmth and elegance to any interior. These 7x3 feet doors are manufactured using seasoned timber frame with particle board core, providing excellent stability and durability. The teak veneer surface showcases beautiful natural grain patterns that enhance the aesthetic appeal. The doors are pre-treated against termites and borers ensuring long-lasting performance. Features smooth edges and precise dimensions for easy installation in standard door frames. The sturdy construction ensures good sound insulation and privacy. Ready for installation with minimal surface preparation required. Can be finished with polish, stain, or paint as per design requirements. Ideal for main doors, bedroom doors, and interior applications in residential and commercial projects. Conforms to quality standards for residential door applications.',
            price: 6800.00,
            currency: 'INR',
            unit: 'piece',
            moq: 2,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ type: 'flush door', size: '7x3 feet', veneer: 'teak', core: 'particle board', finish: 'natural', termiteResistant: true, soundInsulation: 'good', standard: 'IS:2202' }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 72,
            createdAt: new Date('2024-01-27').toISOString(),
            updatedAt: new Date('2024-01-27').toISOString(),
        },
        {
            providerId: 'provider_blr_01',
            title: 'Hindware Sensor Basin Faucet Chrome Auto Shut Off',
            brand: 'Hindware',
            sku: 'HIN-SEN-CHR',
            description: 'Advanced sensor-operated basin faucet from Hindware featuring touchless operation for superior hygiene and water conservation. The infrared sensor detects hand movement and activates water flow automatically, eliminating the need for physical contact. Perfect for commercial washrooms, hospitals, hotels, and smart homes. The chrome finish provides elegant appearance with excellent corrosion resistance. Features adjustable sensor range and automatic shut-off after use to prevent water wastage. Powered by AC adapter or batteries for flexible installation. The aerator provides soft, splash-free water stream with efficient water usage. Easy to install with standard basin connections. The ceramic valve ensures drip-free performance and long service life. Includes all necessary mounting hardware and installation instructions. An ideal solution for modern, hygienic bathroom environments.',
            price: 5500.00,
            currency: 'INR',
            unit: 'piece',
            moq: 1,
            stockStatus: 'limited',
            attributes: JSON.stringify({ type: 'sensor faucet', operation: 'touchless', finish: 'chrome', powerSource: 'AC/battery', autoShutoff: true, sensor: 'infrared', waterSaving: true, warranty: '5 years' }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 68,
            createdAt: new Date('2024-01-28').toISOString(),
            updatedAt: new Date('2024-01-28').toISOString(),
        },
        {
            providerId: 'provider_blr_01',
            title: 'Polycab FR Wires 2.5sqmm 90 Meter Roll Flame Retardant',
            brand: 'Polycab',
            sku: 'POL-FR-2.5',
            description: 'Polycab flame retardant wires manufactured to highest safety standards for residential and commercial electrical installations. This 2.5sqmm wire is ideal for power circuits, lighting, and general electrical wiring applications. The flame retardant PVC insulation meets stringent fire safety norms and self-extinguishes in case of short circuits. Features electrolytic grade copper conductor that ensures excellent conductivity and minimal voltage drop. The 90-meter roll is convenient for standard room wiring with minimal wastage. The insulation is resistant to moisture, chemicals, and mechanical stress. Color-coded for easy identification during installation. Conforms to IS:694 standards with rigorous quality testing at every manufacturing stage. The wire maintains its performance characteristics across temperature variations. Trusted by electricians and contractors for reliable, safe electrical installations. Backed by manufacturer warranty and extensive service network.',
            price: 2850.00,
            currency: 'INR',
            unit: 'roll',
            moq: 5,
            stockStatus: 'in_stock',
            attributes: JSON.stringify({ type: 'FR wire', size: '2.5sqmm', length: '90m', conductor: 'copper', insulation: 'flame retardant PVC', standard: 'IS:694', voltage: '1100V', warranty: '2 years' }),
            city: 'Bangalore',
            deliveryRadiusKm: 30,
            images: JSON.stringify([]),
            pdfUrl: null,
            popularityScore: 85,
            createdAt: new Date('2024-01-29').toISOString(),
            updatedAt: new Date('2024-01-29').toISOString(),
        },
    ];

    await db.insert(catalogs).values(sampleCatalogs);
    
    console.log('✅ Catalogs seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});