import { db } from '@/db';
import { user, profilesProvider } from '@/db/schema';

async function main() {
    const sampleUsers = [
        {
            id: 'admin_vik_01',
            email: 'vikram.admin@hub4estate.com',
            name: 'Vikram Malhotra',
            emailVerified: 1,
            userType: 'admin',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-01'),
            updatedAt: new Date('2024-01-01'),
        },
        {
            id: 'consumer_amit_01',
            email: 'amit.verma@gmail.com',
            name: 'Amit Verma',
            emailVerified: 1,
            userType: 'consumer',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-10'),
            updatedAt: new Date('2024-01-10'),
        },
        {
            id: 'consumer_neha_01',
            email: 'neha.gupta@yahoo.com',
            name: 'Neha Gupta',
            emailVerified: 1,
            userType: 'consumer',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-12'),
            updatedAt: new Date('2024-01-12'),
        },
        {
            id: 'consumer_rahul_01',
            email: 'rahul.mehta@outlook.com',
            name: 'Rahul Mehta',
            emailVerified: 1,
            userType: 'consumer',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-15'),
            updatedAt: new Date('2024-01-15'),
        },
        {
            id: 'consumer_sneha_01',
            email: 'sneha.reddy@gmail.com',
            name: 'Sneha Reddy',
            emailVerified: 1,
            userType: 'consumer',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-18'),
            updatedAt: new Date('2024-01-18'),
        },
        {
            id: 'consumer_karan_01',
            email: 'karan.singh@hotmail.com',
            name: 'Karan Singh',
            emailVerified: 1,
            userType: 'consumer',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-20'),
            updatedAt: new Date('2024-01-20'),
        },
        {
            id: 'provider_jpr_01',
            email: 'contact@jaipurbuilders.com',
            name: 'Jaipur Building Supplies',
            emailVerified: 1,
            userType: 'provider',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-05'),
            updatedAt: new Date('2024-01-05'),
        },
        {
            id: 'provider_del_01',
            email: 'info@delhimarble.com',
            name: 'Delhi Tiles & Marble Hub',
            emailVerified: 1,
            userType: 'provider',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-06'),
            updatedAt: new Date('2024-01-06'),
        },
        {
            id: 'provider_mum_01',
            email: 'sales@mumbaiconstruct.com',
            name: 'Mumbai Construction Co',
            emailVerified: 1,
            userType: 'provider',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-07'),
            updatedAt: new Date('2024-01-07'),
        },
        {
            id: 'provider_blr_01',
            email: 'hello@blrinteriors.com',
            name: 'Bangalore Premium Interiors',
            emailVerified: 1,
            userType: 'provider',
            locale: 'en',
            avatarUrl: null,
            image: null,
            createdAt: new Date('2024-01-08'),
            updatedAt: new Date('2024-01-08'),
        },
    ];

    await db.insert(user).values(sampleUsers);

    const sampleProviderProfiles = [
        {
            userId: 'provider_jpr_01',
            shopName: 'Jaipur Building Supplies',
            phone: '+91-9845672310',
            address: 'Plot 45, Sitapura Industrial Area, Phase II, Jaipur, Rajasthan 302022',
            lat: 26.7721,
            lng: 75.8163,
            categories: ['tiles', 'cement', 'steel', 'marble'],
            brands: ['Kajaria', 'Ultratech', 'JSW Steel', 'ACC'],
            logoUrl: null,
            kycStatus: 'verified',
            trustScore: 92,
            description: 'Leading supplier of premium construction materials in Rajasthan. ISO certified with 15+ years of industry experience.',
            gallery: [],
            createdAt: new Date('2024-01-05').toISOString(),
            updatedAt: new Date('2024-01-05').toISOString(),
        },
        {
            userId: 'provider_del_01',
            shopName: 'Delhi Tiles & Marble Hub',
            phone: '+91-9876234567',
            address: '127, Kirti Nagar Furniture Market, New Delhi 110015',
            lat: 28.6562,
            lng: 77.1482,
            categories: ['tiles', 'marble', 'granite', 'fixtures'],
            brands: ['Kajaria', 'Somany', 'Hindware', 'Jaquar'],
            logoUrl: null,
            kycStatus: 'verified',
            trustScore: 88,
            description: 'Premium tiles and marble showroom. Exclusive dealer for Italian and Spanish tiles.',
            gallery: [],
            createdAt: new Date('2024-01-06').toISOString(),
            updatedAt: new Date('2024-01-06').toISOString(),
        },
        {
            userId: 'provider_mum_01',
            shopName: 'Mumbai Construction Materials',
            phone: '+91-9823456789',
            address: '203, Sion Industrial Estate, Mumbai, Maharashtra 400022',
            lat: 19.0430,
            lng: 72.8637,
            categories: ['cement', 'steel', 'paint', 'wood'],
            brands: ['ACC', 'TATA Steel', 'Asian Paints', 'Century Ply'],
            logoUrl: null,
            kycStatus: 'pending',
            trustScore: 42,
            description: 'Wholesale supplier of construction materials. Bulk orders only.',
            gallery: [],
            createdAt: new Date('2024-01-07').toISOString(),
            updatedAt: new Date('2024-01-07').toISOString(),
        },
        {
            userId: 'provider_blr_01',
            shopName: 'Bangalore Premium Interiors',
            phone: '+91-9741234567',
            address: '89, Whitefield Main Road, Bangalore, Karnataka 560066',
            lat: 12.9698,
            lng: 77.7499,
            categories: ['fixtures', 'electrical', 'lighting', 'sanitary'],
            brands: ['Hindware', 'Havells', 'Legrand', 'Philips'],
            logoUrl: null,
            kycStatus: 'verified',
            trustScore: 85,
            description: 'Premium interior solutions for modern homes. Design consultation available.',
            gallery: [],
            createdAt: new Date('2024-01-08').toISOString(),
            updatedAt: new Date('2024-01-08').toISOString(),
        },
    ];

    await db.insert(profilesProvider).values(sampleProviderProfiles);

    console.log('✅ Users and provider profiles seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});