import { db } from "../index";
import { catalogs, projects, user } from "../schema";

async function seedData() {
  console.log("Starting seed...");

  // Get first user ID from database
  const users = await db.select().from(user).limit(5);
  const userId = users[0]?.id || "demo-user-id";

  // Seed Catalogs
  const catalogData = [
    {
      providerId: userId,
      title: "UltraTech OPC Cement 53 Grade",
      brand: "UltraTech",
      sku: "UTC-OPC-53-50KG",
      description: "Premium quality Ordinary Portland Cement, 53 grade. Ideal for all construction needs including residential, commercial and infrastructure projects.",
      price: 380,
      currency: "INR",
      unit: "bag",
      moq: 50,
      stockStatus: "in",
      city: "Delhi",
      deliveryRadiusKm: 50,
      images: ["https://images.unsplash.com/photo-1590496793907-4d4b0b9b3f5f?w=500"],
      popularityScore: 95,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Kajaria Vitrified Tiles 600x600mm",
      brand: "Kajaria",
      sku: "KAJ-VIT-600",
      description: "Premium vitrified floor tiles with glossy finish. Stain resistant, easy to clean, perfect for living rooms and bedrooms.",
      price: 75,
      currency: "INR",
      unit: "sq.ft",
      moq: 100,
      stockStatus: "in",
      city: "Mumbai",
      deliveryRadiusKm: 30,
      images: ["https://images.unsplash.com/photo-1615874694520-474822394e73?w=500"],
      popularityScore: 88,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Jaquar Bathroom Faucet Chrome",
      brand: "Jaquar",
      sku: "JAQ-FAU-CHR-001",
      description: "Premium chrome-plated bathroom faucet with ceramic disc cartridge. Smooth operation and elegant design.",
      price: 3500,
      currency: "INR",
      unit: "piece",
      moq: 1,
      stockStatus: "in",
      city: "Bangalore",
      deliveryRadiusKm: 40,
      images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500"],
      popularityScore: 82,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Asian Paints Royale Emulsion",
      brand: "Asian Paints",
      sku: "AP-ROY-EMU-20L",
      description: "Premium interior emulsion paint with advanced stain guard technology. Rich, luxurious finish with excellent coverage.",
      price: 4200,
      currency: "INR",
      unit: "20L bucket",
      moq: 1,
      stockStatus: "in",
      city: "Jaipur",
      deliveryRadiusKm: 25,
      images: ["https://images.unsplash.com/photo-1562259949-e8e7689d7828?w=500"],
      popularityScore: 90,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "TMT Steel Bars Fe 500D",
      brand: "Tata Steel",
      sku: "TATA-TMT-500D-12MM",
      description: "High strength TMT bars for reinforced concrete construction. Earthquake resistant with superior bendability.",
      price: 58,
      currency: "INR",
      unit: "kg",
      moq: 500,
      stockStatus: "in",
      city: "Pune",
      deliveryRadiusKm: 60,
      images: ["https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?w=500"],
      popularityScore: 92,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Somany Ceramic Wall Tiles",
      brand: "Somany",
      sku: "SOM-CER-300x450",
      description: "Designer ceramic wall tiles for kitchen and bathroom. Glossy finish, easy to maintain.",
      price: 45,
      currency: "INR",
      unit: "sq.ft",
      moq: 50,
      stockStatus: "limited",
      city: "Delhi",
      deliveryRadiusKm: 35,
      images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500"],
      popularityScore: 78,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Kohler Sanitaryware Set",
      brand: "Kohler",
      sku: "KOH-SAN-SET-001",
      description: "Complete bathroom sanitaryware set including WC, washbasin and accessories. Premium quality porcelain.",
      price: 28500,
      currency: "INR",
      unit: "set",
      moq: 1,
      stockStatus: "in",
      city: "Mumbai",
      deliveryRadiusKm: 50,
      images: ["https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?w=500"],
      popularityScore: 85,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Havells Modular Switches",
      brand: "Havells",
      sku: "HAV-MOD-SW-WHITE",
      description: "Premium modular electrical switches and sockets. Stylish white finish with safety shutters.",
      price: 450,
      currency: "INR",
      unit: "piece",
      moq: 10,
      stockStatus: "in",
      city: "Bangalore",
      deliveryRadiusKm: 40,
      images: ["https://images.unsplash.com/photo-1621905252507-b35492cc74b4?w=500"],
      popularityScore: 87,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Polycab Electrical Wires 2.5sq mm",
      brand: "Polycab",
      sku: "POL-WIRE-2.5MM",
      description: "High quality copper electrical wiring for residential and commercial use. ISI certified.",
      price: 2800,
      currency: "INR",
      unit: "90m coil",
      moq: 1,
      stockStatus: "in",
      city: "Delhi",
      deliveryRadiusKm: 45,
      images: ["https://images.unsplash.com/photo-1473341304170-971dccb5ac1e?w=500"],
      popularityScore: 91,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "UPVC Window Frames",
      brand: "Fenesta",
      sku: "FEN-UPVC-WIN-5X4",
      description: "Energy efficient UPVC window frames with double glazing. Weather resistant and low maintenance.",
      price: 12500,
      currency: "INR",
      unit: "5x4 feet",
      moq: 2,
      stockStatus: "in",
      city: "Pune",
      deliveryRadiusKm: 30,
      images: ["https://images.unsplash.com/photo-1545259741-2ea3ebf61fa3?w=500"],
      popularityScore: 80,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Wooden Flush Door Teak",
      brand: "Greenply",
      sku: "GRN-DOOR-TEAK-7X3",
      description: "Premium teak veneer flush door. Termite resistant with elegant natural wood finish.",
      price: 8500,
      currency: "INR",
      unit: "7x3 feet",
      moq: 1,
      stockStatus: "in",
      city: "Jaipur",
      deliveryRadiusKm: 25,
      images: ["https://images.unsplash.com/photo-1519710164239-da123dc03ef4?w=500"],
      popularityScore: 83,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Philips LED Bulbs 9W",
      brand: "Philips",
      sku: "PHI-LED-9W-COOL",
      description: "Energy efficient LED bulbs with cool daylight. Long lasting with 50,000 hour life.",
      price: 180,
      currency: "INR",
      unit: "piece",
      moq: 10,
      stockStatus: "in",
      city: "Bangalore",
      deliveryRadiusKm: 50,
      images: ["https://images.unsplash.com/photo-1550985543-49bee3167284?w=500"],
      popularityScore: 89,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Hindware Kitchen Sink SS",
      brand: "Hindware",
      sku: "HIN-SINK-SS-24X18",
      description: "Stainless steel kitchen sink with drain basket. Corrosion resistant and easy to clean.",
      price: 4200,
      currency: "INR",
      unit: "piece",
      moq: 1,
      stockStatus: "in",
      city: "Mumbai",
      deliveryRadiusKm: 35,
      images: ["https://images.unsplash.com/photo-1584622650111-993a426fbf0a?w=500"],
      popularityScore: 81,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Berger WeatherCoat Exterior Paint",
      brand: "Berger",
      sku: "BER-WC-EXT-20L",
      description: "Premium exterior emulsion paint with weather shield technology. UV resistant and long lasting.",
      price: 5500,
      currency: "INR",
      unit: "20L bucket",
      moq: 1,
      stockStatus: "in",
      city: "Delhi",
      deliveryRadiusKm: 40,
      images: ["https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500"],
      popularityScore: 86,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      providerId: userId,
      title: "Red Clay Bricks Standard",
      brand: "Local Supplier",
      sku: "BRICK-RED-STD",
      description: "High quality red clay bricks for construction. Standard size 230x110x75mm. Strong and durable.",
      price: 8,
      currency: "INR",
      unit: "piece",
      moq: 1000,
      stockStatus: "in",
      city: "Jaipur",
      deliveryRadiusKm: 50,
      images: ["https://images.unsplash.com/photo-1590496793907-4d4b0b9b3f5f?w=500"],
      popularityScore: 75,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  console.log("Inserting catalogs...");
  await db.insert(catalogs).values(catalogData);
  console.log(`✅ Inserted ${catalogData.length} catalogs`);

  // Seed Projects
  const projectData = [
    {
      ownerId: userId,
      title: "Modern 3BHK Apartment Construction",
      address: "Sector 45, Gurgaon",
      city: "Gurgaon",
      budget: 4500000,
      currency: "INR",
      status: "planning",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      ownerId: userId,
      title: "Villa Construction Project",
      address: "Whitefield, Bangalore",
      city: "Bangalore",
      budget: 8500000,
      currency: "INR",
      status: "in_progress",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      ownerId: userId,
      title: "Office Space Renovation",
      address: "Bandra West, Mumbai",
      city: "Mumbai",
      budget: 2500000,
      currency: "INR",
      status: "planning",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      ownerId: userId,
      title: "Boutique Hotel Interior Work",
      address: "Civil Lines, Jaipur",
      city: "Jaipur",
      budget: 6500000,
      currency: "INR",
      status: "in_progress",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      ownerId: userId,
      title: "Independent House Construction",
      address: "Dwarka, Delhi",
      city: "Delhi",
      budget: 5500000,
      currency: "INR",
      status: "planning",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      ownerId: userId,
      title: "Retail Shop Interior Design",
      address: "Koregaon Park, Pune",
      city: "Pune",
      budget: 1200000,
      currency: "INR",
      status: "completed",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      ownerId: userId,
      title: "Farmhouse Construction",
      address: "Sohna Road, Gurgaon",
      city: "Gurgaon",
      budget: 12000000,
      currency: "INR",
      status: "in_progress",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      ownerId: userId,
      title: "Restaurant Kitchen Setup",
      address: "Indiranagar, Bangalore",
      city: "Bangalore",
      budget: 1800000,
      currency: "INR",
      status: "planning",
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  console.log("Inserting projects...");
  await db.insert(projects).values(projectData);
  console.log(`✅ Inserted ${projectData.length} projects`);

  console.log("✅ Seed completed successfully!");
}

seedData()
  .then(() => {
    console.log("Done!");
    process.exit(0);
  })
  .catch((error) => {
    console.error("Seed failed:", error);
    process.exit(1);
  });